    all:
      vars:
        student_number:             "000"
        ansible_user:               student
        monitor_address_block:      10.0.0.0/12
        public_network:             10.0.0.0/12
        ansible_python_interpreter: /usr/bin/python3
      children:  
        clients:
          hosts:
            localhost
        mons:
          hosts:
            master1:
              ansible_host: ceph-{{ student_number }}-master-01.localdomain 
            master2:
              ansible_host: ceph-{{ student_number }}-master-02.localdomain 
            master3:
              ansible_host: ceph-{{ student_number }}-master-03.localdomain 
        osds:
          hosts:
            node1:
              ansible_host: ceph-{{ student_number }}-node-01.localdomain 
            node2:
              ansible_host: ceph-{{ student_number }}-node-02.localdomain 
            node3:
              ansible_host: ceph-{{ student_number }}-node-03.localdomain
