    all:
      vars:
        studentnumber:              "999"
        ansible_user:               student
        monitor_address_block:      10.0.0.0/12
        public_network:             10.0.0.0/12
        ansible_python_interpreter: /usr/bin/python3
      children:  
        clients:
          hosts:
            localhost
        mons:
          hosts:
            master1:
              vars: 
                ansible_host:       ceph-{{ studentnumber }}-master-01.localdomain 
            master2:
              vars:
                ansible_host:       ceph-{{ studentnumber }}-master-02.localdomain 
            master3:
              vars
               ansible_host:        ceph-{{ studentnumber }}-master-03.localdomain 
        osds:
          hosts:
            node1:
              vars: 
                ansible_host:       ceph-{{ studentnumber }}-node-01.localdomain 
            node2
              vars: 
                ansible_host:       ceph-{{ studentnumber }}-node-02.localdomain 
            node3:
              vars: 
                ansible_host:       ceph-{{ studentnumber }}-node-03.localdomain
